### ISSUE TITLE
Split create database from other statements

### ISSUE THREAD

**Issue by PaulVelthuis93** [bbrumm/databasestar#10]
As most databases need to be able to roll back, it is recommended to have the create database in a separate script.

https://github.com/bbrumm/databasestar/blob/d6fc75697d9c89c482aa1979ed57d566515f0e4d/sample_databases/sample_db_gravity/gravity_postgres/01_postgres_create.sql#L1C1-L2C1

**Comment by bbrumm** [comment]
Thanks Paul, I've merged this now.
