### ISSUE TITLE
Error in movie.sql script in MYSQL

### ISSUE THREAD

**Issue by BadrinathKulkarni** [bbrumm/databasestar#3]
Date format is 0000-00-00

movie_id :  380097

(380097,'America Is Still the Place',0,'','1971 post civil rights San Francisco seemed like the perfect place for a black Korean War veteran and his family to realize their dream of economic independence and his own chance to be his a \"boss\". Charlie Walker would soon find out how naive he was. In a city full of impostors and naysayers, he refused to take \"No\" for an answer. Until a catastrophic disaster opened a door that had never been open to a black man before. This is a story about what happened when he stepped through that door, with both feet!.',0.000000,'**0000-00-00**',0,0,'Released','',0.00,0),

**Comment by bbrumm** [comment]
Thanks for letting me know! I've updated the script.
